"""model: group

Revision ID: fae8c2af6632
Revises: 254a1eee69c9
Create Date: 2026-06-08 20:30:28.797579

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fae8c2af6632"
down_revision: Union[str, Sequence[str], None] = "254a1eee69c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("speciality_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=10), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "shift",
            postgresql.ENUM("first", "second", name="shift_type"),
            nullable=False,
        ),
        sa.Column("student_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "student_count BETWEEN 1 AND 35",
            name=op.f("ck_groups_ck_group_student_count_range"),
        ),
        sa.CheckConstraint(
            "year BETWEEN 1 AND 7", name=op.f("ck_groups_ck_group_year_range")
        ),
        sa.ForeignKeyConstraint(
            ["speciality_id"],
            ["specialities.id"],
            name=op.f("fk_groups_speciality_id_specialities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
        sa.UniqueConstraint("name", name=op.f("uq_groups_name")),
        sa.UniqueConstraint(
            "speciality_id", "name", "year", name="uq_group_speciality_name_year"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("groups")
    # ### end Alembic commands ###
    sa.Enum(name="shift_type").drop(op.get_bind(), checkfirst=True)
