"""add current_semester_id to group model

Revision ID: 757bbf3d82af
Revises: ce894f14c036
Create Date: 2026-06-12 18:38:04.428902

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "757bbf3d82af"
down_revision: Union[str, Sequence[str], None] = "ce894f14c036"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups", sa.Column("current_semester_id", sa.UUID(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_groups_current_semester_id_semesters"),
        "groups",
        "semesters",
        ["current_semester_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_groups_current_semester_id_semesters"),
        "groups",
        type_="foreignkey",
    )
    op.drop_column("groups", "current_semester_id")
    # ### end Alembic commands ###
