"""add mixins: practice

Revision ID: 48948522b0be
Revises: 41fda460b89c
Create Date: 2026-06-18 15:13:40.127567

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "48948522b0be"
down_revision: Union[str, Sequence[str], None] = "41fda460b89c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "practices",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "practices",
        sa.Column(
            "created_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.add_column(
        "practices",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "practices",
        sa.Column(
            "updated_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_practices_updated_by_users"),
        "practices",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_practices_created_by_users"),
        "practices",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_practices_created_by_users"), "practices", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_practices_updated_by_users"), "practices", type_="foreignkey"
    )
    op.drop_column("practices", "updated_by")
    op.drop_column("practices", "updated_at")
    op.drop_column("practices", "created_by")
    op.drop_column("practices", "created_at")
    # ### end Alembic commands ###
