"""unlimited number of practice in semester

Revision ID: ce894f14c036
Revises: 7f32c8bc29bd
Create Date: 2026-06-12 18:00:04.787742

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "ce894f14c036"
down_revision: Union[str, Sequence[str], None] = "7f32c8bc29bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("semesters", "practice_end_date")
    op.drop_column("semesters", "practice_start_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "semesters",
        sa.Column(
            "practice_start_date",
            sa.DATE(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "semesters",
        sa.Column(
            "practice_end_date", sa.DATE(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
