"""add mixins: group

Revision ID: 41fda460b89c
Revises: 399e8e82bac4
Create Date: 2026-06-18 15:11:38.446720

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "41fda460b89c"
down_revision: Union[str, Sequence[str], None] = "399e8e82bac4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "created_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "updated_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_groups_created_by_users"),
        "groups",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_groups_updated_by_users"),
        "groups",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_groups_updated_by_users"), "groups", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_groups_created_by_users"), "groups", type_="foreignkey"
    )
    op.drop_column("groups", "updated_by")
    op.drop_column("groups", "updated_at")
    op.drop_column("groups", "created_by")
    op.drop_column("groups", "created_at")
    # ### end Alembic commands ###
