"""add mixins: subject

Revision ID: 9018cde120f4
Revises: 4b15e5091794
Create Date: 2026-06-18 15:31:11.984986

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "9018cde120f4"
down_revision: Union[str, Sequence[str], None] = "4b15e5091794"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subjects",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "subjects",
        sa.Column(
            "created_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.add_column(
        "subjects",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "subjects",
        sa.Column(
            "updated_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_subjects_created_by_users"),
        "subjects",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_subjects_updated_by_users"),
        "subjects",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_subjects_updated_by_users"), "subjects", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_subjects_created_by_users"), "subjects", type_="foreignkey"
    )
    op.drop_column("subjects", "updated_by")
    op.drop_column("subjects", "updated_at")
    op.drop_column("subjects", "created_by")
    op.drop_column("subjects", "created_at")
    # ### end Alembic commands ###
