"""model: specialty

Revision ID: 254a1eee69c9
Revises: b12a8d7aeef6
Create Date: 2026-06-07 15:46:19.565751

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "254a1eee69c9"
down_revision: Union[str, Sequence[str], None] = "b12a8d7aeef6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specialties",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("code", sa.String(length=15), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_specialties")),
        sa.UniqueConstraint("name", "code", name="uq_specialty_name_code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("specialties")
    # ### end Alembic commands ###
