"""add mixins: speciality plus column duration

Revision ID: 4b15e5091794
Revises: 6c6d6be5a8af
Create Date: 2026-06-18 15:29:48.900860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "4b15e5091794"
down_revision: Union[str, Sequence[str], None] = "6c6d6be5a8af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "specialities",
        sa.Column("study_years", sa.String(length=20), nullable=False),
    )
    op.add_column(
        "specialities",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "specialities",
        sa.Column(
            "created_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.add_column(
        "specialities",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "specialities",
        sa.Column(
            "updated_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_specialities_updated_by_users"),
        "specialities",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_specialities_created_by_users"),
        "specialities",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_specialities_created_by_users"),
        "specialities",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_specialities_updated_by_users"),
        "specialities",
        type_="foreignkey",
    )
    op.drop_column("specialities", "updated_by")
    op.drop_column("specialities", "updated_at")
    op.drop_column("specialities", "created_by")
    op.drop_column("specialities", "created_at")
    op.drop_column("specialities", "study_years")
    # ### end Alembic commands ###
