"""model: time slots and semesters

Revision ID: 56ce42a3fbd8
Revises: 1eae540eaffc
Create Date: 2026-06-07 14:47:27.343103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "56ce42a3fbd8"
down_revision: Union[str, Sequence[str], None] = "1eae540eaffc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "semesters",
        sa.Column("academic_year", sa.Integer(), nullable=False),
        sa.Column("semester_number", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("session_start_date", sa.Date(), nullable=False),
        sa.Column("session_end_date", sa.Date(), nullable=False),
        sa.Column("practice_start_date", sa.Date(), nullable=False),
        sa.Column("practice_end_date", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "academic_year BETWEEN 1 AND 7",
            name=op.f("ck_semesters_check_academic_year_range"),
        ),
        sa.CheckConstraint(
            "end_date > start_date",
            name=op.f("ck_semesters_check_semester_dates"),
        ),
        sa.CheckConstraint(
            "practice_end_date > practice_start_date",
            name=op.f("ck_semesters_check_practice_dates"),
        ),
        sa.CheckConstraint(
            "semester_number BETWEEN 1 AND 14",
            name=op.f("ck_semesters_check_semester_number_range"),
        ),
        sa.CheckConstraint(
            "session_end_date > session_start_date",
            name=op.f("ck_semesters_check_session_dates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_semesters")),
        sa.UniqueConstraint(
            "academic_year",
            "semester_number",
            name="unique_semester_year_number",
        ),
    )
    op.create_table(
        "time_slots",
        sa.Column(
            "slot_number",
            postgresql.ENUM(
                "one",
                "two",
                "three",
                "four",
                "five",
                "six",
                "seven",
                "eight",
                "nine",
                name="slot_number",
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "end_time > start_time",
            name=op.f("ck_time_slots_check_time_order"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_time_slots")),
        sa.UniqueConstraint("slot_number", name="slot_number_unique"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("time_slots")
    op.drop_table("semesters")
    sa.Enum(
        name="slot_number"
        ).drop(
        op.get_bind(),
        checkfirst=True
        )
    # ### end Alembic commands ###
