"""model: schedule plan and item

Revision ID: ac6f75fd24f2
Revises: 5157600a5c17
Create Date: 2026-06-08 21:53:22.904664

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ac6f75fd24f2"
down_revision: Union[str, Sequence[str], None] = "5157600a5c17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_plans",
        sa.Column("speciality_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("semester_id", sa.UUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("lecture_hours", sa.Integer(), nullable=False),
        sa.Column("practice_hours", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "lecture_hours > 0 AND lecture_hours <= 2000",
            name=op.f("ck_schedule_plans_ck_lecture_hours_range"),
        ),
        sa.CheckConstraint(
            "lecture_hours > 0 OR practice_hours > 0",
            name=op.f("ck_schedule_plans_ck_at_least_one_hour_type"),
        ),
        sa.CheckConstraint(
            "practice_hours > 0 AND practice_hours <= 1000",
            name=op.f("ck_schedule_plans_ck_practice_hours_range"),
        ),
        sa.CheckConstraint(
            "year BETWEEN 1 AND 7",
            name=op.f("ck_schedule_plans_ck_schedule_plan_year_range"),
        ),
        sa.ForeignKeyConstraint(
            ["semester_id"],
            ["semesters.id"],
            name=op.f("fk_schedule_plans_semester_id_semesters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["speciality_id"],
            ["specialities.id"],
            name=op.f("fk_schedule_plans_speciality_id_specialities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_schedule_plans_subject_id_subjects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_plans")),
        sa.UniqueConstraint(
            "speciality_id",
            "subject_id",
            "semester_id",
            name="uq_schedule_plan_speciality_subject_semester",
        ),
    )
    op.create_table(
        "schedule_items",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("semester_id", sa.UUID(), nullable=False),
        sa.Column("time_slot_id", sa.UUID(), nullable=False),
        sa.Column("class_date", sa.Date(), nullable=False),
        sa.Column(
            "activity_type",
            postgresql.ENUM(
                "lecture",
                "seminar",
                "laboratory_work",
                "practical_work",
                name="activity_type",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_schedule_items_group_id_groups"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name=op.f("fk_schedule_items_room_id_rooms"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["semester_id"],
            ["semesters.id"],
            name=op.f("fk_schedule_items_semester_id_semesters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_schedule_items_subject_id_subjects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_schedule_items_teacher_id_teachers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["time_slot_id"],
            ["time_slots.id"],
            name=op.f("fk_schedule_items_time_slot_id_time_slots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_items")),
        sa.UniqueConstraint(
            "group_id",
            "class_date",
            "time_slot_id",
            name="uq_schedule_group_date_time",
        ),
        sa.UniqueConstraint(
            "room_id",
            "class_date",
            "time_slot_id",
            name="uq_schedule_room_date_time",
        ),
        sa.UniqueConstraint(
            "teacher_id",
            "class_date",
            "time_slot_id",
            name="uq_schedule_teacher_date_time",
        ),
    )
    op.add_column(
        "groups", sa.Column("speciality_id", sa.UUID(), nullable=False)
    )
    op.drop_constraint(
        op.f("uq_group_specialty_name_year"), "groups", type_="unique"
    )
    op.create_unique_constraint(
        "uq_group_speciality_name_year",
        "groups",
        ["speciality_id", "name", "year"],
    )
    op.drop_constraint(
        op.f("fk_groups_specialty_id_specialties"),
        "groups",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_groups_speciality_id_specialities"),
        "groups",
        "specialities",
        ["speciality_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("groups", "specialty_id")
    op.drop_constraint(
        op.f("uq_specialty_name_code"), "specialities", type_="unique"
    )
    op.create_unique_constraint(
        "uq_speciality_name_code", "specialities", ["name", "code"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_speciality_name_code", "specialities", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_specialty_name_code"),
        "specialities",
        ["name", "code"],
        postgresql_nulls_not_distinct=False,
    )
    op.add_column(
        "groups",
        sa.Column(
            "specialty_id", sa.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_groups_speciality_id_specialities"),
        "groups",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_groups_specialty_id_specialties"),
        "groups",
        "specialities",
        ["specialty_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        "uq_group_speciality_name_year", "groups", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_group_specialty_name_year"),
        "groups",
        ["specialty_id", "name", "year"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("groups", "speciality_id")
    op.drop_table("schedule_items")
    op.drop_table("schedule_plans")
    # ### end Alembic commands ###
