"""add mixins: building

Revision ID: 399e8e82bac4
Revises: 757bbf3d82af
Create Date: 2026-06-18 15:07:34.088211

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "399e8e82bac4"
down_revision: Union[str, Sequence[str], None] = "757bbf3d82af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "buildings",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "buildings",
        sa.Column(
            "created_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.add_column(
        "buildings",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "buildings",
        sa.Column(
            "updated_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_buildings_updated_by_users"),
        "buildings",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_buildings_created_by_users"),
        "buildings",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "rooms",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "rooms",
        sa.Column(
            "created_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.add_column(
        "rooms",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "rooms",
        sa.Column(
            "updated_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_rooms_updated_by_users"),
        "rooms",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_rooms_created_by_users"),
        "rooms",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_rooms_created_by_users"), "rooms", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_rooms_updated_by_users"), "rooms", type_="foreignkey"
    )
    op.drop_column("rooms", "updated_by")
    op.drop_column("rooms", "updated_at")
    op.drop_column("rooms", "created_by")
    op.drop_column("rooms", "created_at")
    op.drop_constraint(
        op.f("fk_buildings_created_by_users"), "buildings", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_buildings_updated_by_users"), "buildings", type_="foreignkey"
    )
    op.drop_column("buildings", "updated_by")
    op.drop_column("buildings", "updated_at")
    op.drop_column("buildings", "created_by")
    op.drop_column("buildings", "created_at")
    # ### end Alembic commands ###
