"""model: teacher and teacher_availability

Revision ID: b12a8d7aeef6
Revises: 56ce42a3fbd8
Create Date: 2026-06-07 15:31:20.410546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b12a8d7aeef6"
down_revision: Union[str, Sequence[str], None] = "56ce42a3fbd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teachers",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("middle_name", sa.String(length=30), nullable=True),
        sa.Column("last_name", sa.String(length=30), nullable=False),
        sa.Column("is_full_time", sa.Boolean(), nullable=False),
        sa.Column("is_invited", sa.Boolean(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hired_date", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "NOT (is_full_time = TRUE AND is_invited = TRUE)",
            name=op.f("ck_teachers_check_teacher_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teachers")),
        sa.UniqueConstraint("email", name=op.f("uq_teachers_email")),
        sa.UniqueConstraint("phone", name=op.f("uq_teachers_phone")),
    )
    op.create_table(
        "teacher_availability",
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.Column(
            "day_of_week",
            postgresql.ENUM(
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday",
                name="day_of_week",
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "end_time > start_time",
            name=op.f("ck_teacher_availability_check_time_order_in_availability"),
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_teacher_availability_teacher_id_teachers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teacher_availability")),
        sa.UniqueConstraint(
            "teacher_id",
            "day_of_week",
            "start_time",
            name="uq_teacher_day_time",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("teacher_availability")
    op.drop_table("teachers")
    sa.Enum(name="day_of_week").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
