"""add indexes and description to semester

Revision ID: 7f32c8bc29bd
Revises: 89a559adcc2d
Create Date: 2026-06-09 20:00:07.988782

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "7f32c8bc29bd"
down_revision: Union[str, Sequence[str], None] = "89a559adcc2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teacher_subjects",
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_teacher_subjects_subject_id_subjects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_teacher_subjects_teacher_id_teachers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teacher_subjects")),
        sa.UniqueConstraint(
            "teacher_id",
            "subject_id",
            name="uniq_teacher_id_subject_id_and_teacher_id",
        ),
    )
    op.create_index(
        "idx_teacher_subject_subject",
        "teacher_subjects",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        "idx_teacher_subject_teacher",
        "teacher_subjects",
        ["teacher_id"],
        unique=False,
    )
    op.create_index("idx_building_name", "buildings", ["name"], unique=False)
    op.create_index(
        "idx_group_speciality", "groups", ["speciality_id"], unique=False
    )
    op.create_index(
        "idx_group_speciality_year",
        "groups",
        ["speciality_id", "year"],
        unique=False,
    )
    op.create_index("idx_group_year", "groups", ["year"], unique=False)
    op.create_index(
        "idx_practice_dates",
        "practices",
        ["practice_start_date", "practice_end_date"],
        unique=False,
    )
    op.create_index(
        "idx_practice_semester", "practices", ["semester_id"], unique=False
    )
    op.create_index("idx_practice_type", "practices", ["type"], unique=False)
    op.create_index(
        "idx_room_building", "rooms", ["building_id"], unique=False
    )
    op.create_index("idx_room_capacity", "rooms", ["capacity"], unique=False)
    op.create_index("idx_room_type", "rooms", ["room_type"], unique=False)
    op.create_index(
        "idx_schedule_item_activity_type",
        "schedule_items",
        ["activity_type"],
        unique=False,
    )
    op.create_index(
        "idx_schedule_item_class_date",
        "schedule_items",
        ["class_date"],
        unique=False,
    )
    op.create_index(
        "idx_schedule_item_group_date",
        "schedule_items",
        ["group_id", "class_date"],
        unique=False,
    )
    op.create_index(
        "idx_schedule_item_room_date",
        "schedule_items",
        ["room_id", "class_date"],
        unique=False,
    )
    op.create_index(
        "idx_schedule_item_semester",
        "schedule_items",
        ["semester_id"],
        unique=False,
    )
    op.create_index(
        "idx_schedule_item_teacher_date",
        "schedule_items",
        ["teacher_id", "class_date"],
        unique=False,
    )
    op.create_index(
        "idx_schedule_plan_semester",
        "schedule_plans",
        ["semester_id"],
        unique=False,
    )
    op.create_index(
        "idx_schedule_plan_speciality",
        "schedule_plans",
        ["speciality_id"],
        unique=False,
    )
    op.create_index(
        "idx_schedule_plan_speciality_semester",
        "schedule_plans",
        ["speciality_id", "semester_id"],
        unique=False,
    )
    op.create_index(
        "idx_schedule_plan_subject",
        "schedule_plans",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        "idx_schedule_plan_year", "schedule_plans", ["year"], unique=False
    )
    op.add_column(
        "semesters",
        sa.Column("description", sa.String(length=150), nullable=True),
    )
    op.create_index(
        "idx_semester_academic_year",
        "semesters",
        ["academic_year"],
        unique=False,
    )
    op.create_index(
        "idx_semester_dates",
        "semesters",
        ["start_date", "end_date"],
        unique=False,
    )
    op.create_index(
        "idx_semester_number", "semesters", ["semester_number"], unique=False
    )
    op.create_index(
        "idx_teacher_availability_day_time",
        "teacher_availability",
        ["day_of_week", "start_time", "end_time"],
        unique=False,
    )
    op.create_index(
        "idx_teacher_availability_teacher",
        "teacher_availability",
        ["teacher_id"],
        unique=False,
    )
    op.create_index(
        "idx_teacher_substitution_created_at",
        "teacher_substitutions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_teacher_substitution_new_teacher",
        "teacher_substitutions",
        ["new_teacher_id"],
        unique=False,
    )
    op.create_index(
        "idx_teacher_substitution_old_teacher",
        "teacher_substitutions",
        ["old_teacher_id"],
        unique=False,
    )
    op.create_index(
        "idx_teacher_substitution_schedule_item",
        "teacher_substitutions",
        ["schedule_item_id"],
        unique=False,
    )
    op.create_index(
        "idx_time_slot_number", "time_slots", ["slot_number"], unique=False
    )
    op.create_index(
        "idx_time_slot_start_time", "time_slots", ["start_time"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_time_slot_start_time", table_name="time_slots")
    op.drop_index("idx_time_slot_number", table_name="time_slots")
    op.drop_index(
        "idx_teacher_substitution_schedule_item",
        table_name="teacher_substitutions",
    )
    op.drop_index(
        "idx_teacher_substitution_old_teacher",
        table_name="teacher_substitutions",
    )
    op.drop_index(
        "idx_teacher_substitution_new_teacher",
        table_name="teacher_substitutions",
    )
    op.drop_index(
        "idx_teacher_substitution_created_at",
        table_name="teacher_substitutions",
    )
    op.drop_index(
        "idx_teacher_availability_teacher", table_name="teacher_availability"
    )
    op.drop_index(
        "idx_teacher_availability_day_time", table_name="teacher_availability"
    )
    op.drop_index("idx_semester_number", table_name="semesters")
    op.drop_index("idx_semester_dates", table_name="semesters")
    op.drop_index("idx_semester_academic_year", table_name="semesters")
    op.drop_column("semesters", "description")
    op.drop_index("idx_schedule_plan_year", table_name="schedule_plans")
    op.drop_index("idx_schedule_plan_subject", table_name="schedule_plans")
    op.drop_index(
        "idx_schedule_plan_speciality_semester", table_name="schedule_plans"
    )
    op.drop_index("idx_schedule_plan_speciality", table_name="schedule_plans")
    op.drop_index("idx_schedule_plan_semester", table_name="schedule_plans")
    op.drop_index(
        "idx_schedule_item_teacher_date", table_name="schedule_items"
    )
    op.drop_index("idx_schedule_item_semester", table_name="schedule_items")
    op.drop_index("idx_schedule_item_room_date", table_name="schedule_items")
    op.drop_index("idx_schedule_item_group_date", table_name="schedule_items")
    op.drop_index("idx_schedule_item_class_date", table_name="schedule_items")
    op.drop_index(
        "idx_schedule_item_activity_type", table_name="schedule_items"
    )
    op.drop_index("idx_room_type", table_name="rooms")
    op.drop_index("idx_room_capacity", table_name="rooms")
    op.drop_index("idx_room_building", table_name="rooms")
    op.drop_index("idx_practice_type", table_name="practices")
    op.drop_index("idx_practice_semester", table_name="practices")
    op.drop_index("idx_practice_dates", table_name="practices")
    op.drop_index("idx_group_year", table_name="groups")
    op.drop_index("idx_group_speciality_year", table_name="groups")
    op.drop_index("idx_group_speciality", table_name="groups")
    op.drop_index("idx_building_name", table_name="buildings")
    op.drop_index("idx_teacher_subject_teacher", table_name="teacher_subjects")
    op.drop_index("idx_teacher_subject_subject", table_name="teacher_subjects")
    op.drop_table("teacher_subjects")
    # ### end Alembic commands ###
