"""add mixins: time

Revision ID: 170541bee330
Revises: 6ff92647e050
Create Date: 2026-06-18 15:33:34.977637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "170541bee330"
down_revision: Union[str, Sequence[str], None] = "6ff92647e050"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "semesters",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "semesters",
        sa.Column(
            "created_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.add_column(
        "semesters",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "semesters",
        sa.Column(
            "updated_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_semesters_updated_by_users"),
        "semesters",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_semesters_created_by_users"),
        "semesters",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "time_slots",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "time_slots",
        sa.Column(
            "created_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.add_column(
        "time_slots",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "time_slots",
        sa.Column(
            "updated_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_time_slots_created_by_users"),
        "time_slots",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_time_slots_updated_by_users"),
        "time_slots",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_time_slots_updated_by_users"),
        "time_slots",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_time_slots_created_by_users"),
        "time_slots",
        type_="foreignkey",
    )
    op.drop_column("time_slots", "updated_by")
    op.drop_column("time_slots", "updated_at")
    op.drop_column("time_slots", "created_by")
    op.drop_column("time_slots", "created_at")
    op.drop_constraint(
        op.f("fk_semesters_created_by_users"), "semesters", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_semesters_updated_by_users"), "semesters", type_="foreignkey"
    )
    op.drop_column("semesters", "updated_by")
    op.drop_column("semesters", "updated_at")
    op.drop_column("semesters", "created_by")
    op.drop_column("semesters", "created_at")
    # ### end Alembic commands ###
