"""model: teacher substitution

Revision ID: 89a559adcc2d
Revises: ac6f75fd24f2
Create Date: 2026-06-08 22:10:55.307509

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "89a559adcc2d"
down_revision: Union[str, Sequence[str], None] = "ac6f75fd24f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teacher_substitutions",
        sa.Column("schedule_item_id", sa.UUID(), nullable=False),
        sa.Column("old_teacher_id", sa.UUID(), nullable=False),
        sa.Column("new_teacher_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "old_teacher_id != new_teacher_id",
            name=op.f(
                "ck_teacher_substitutions_ck_teacher_substitution_diff_teachers"
            ),
        ),
        sa.CheckConstraint(
            "reason IS NULL OR length(trim(reason)) > 0",
            name=op.f(
                "ck_teacher_substitutions_ck_teacher_substitution_reason_not_empty"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["new_teacher_id"],
            ["teachers.id"],
            name=op.f("fk_teacher_substitutions_new_teacher_id_teachers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["old_teacher_id"],
            ["teachers.id"],
            name=op.f("fk_teacher_substitutions_old_teacher_id_teachers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_item_id"],
            ["schedule_items.id"],
            name=op.f(
                "fk_teacher_substitutions_schedule_item_id_schedule_items"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teacher_substitutions")),
        sa.UniqueConstraint(
            "schedule_item_id",
            name=op.f("uq_teacher_substitutions_schedule_item_id"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("teacher_substitutions")
    # ### end Alembic commands ###
